# Generated by Django 4.2.23 on 2025-07-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='프로젝트명')),
                ('total_room_count', models.IntegerField(default=0, verbose_name='실개수')),
                ('total_area', models.FloatField(default=0.0, verbose_name='연면적_m2')),
                ('ground_level', models.IntegerField(default=0, verbose_name='지상층수')),
                ('basement_level', models.IntegerField(default=0, verbose_name='지하층수')),
                ('site_area', models.FloatField(default=0.0, verbose_name='대지면적_m2')),
                ('budget', models.FloatField(default=0.0, verbose_name='예산_원')),
            ],
        ),
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='총공사비_원')),
                ('a_cost', models.FloatField(default=0.0, verbose_name='건축공사비_원')),
                ('etc_cost', models.FloatField(default=0.0, verbose_name='기타공사비_원')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_by_input.inputdata')),
            ],
        ),
    ]
