# Generated by Django 4.2.23 on 2025-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='프로젝트명')),
                ('ifc_file', models.FileField(upload_to='ifc_files/', verbose_name='IFC 파일')),
            ],
        ),
    ]
