# Generated by Django 4.2.23 on 2025-07-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd_by_ifc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=100)),
                ('ifc_file', models.FileField(upload_to='ifc_files/')),
                ('converted_obj', models.FileField(blank=True, null=True, upload_to='converted_objs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectIdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_id', models.CharField(max_length=100)),
                ('global_id', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd_by_ifc.project')),
            ],
        ),
    ]
