# Generated by Django 4.2.23 on 2025-07-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd_by_ifc', '0002_project_objectidmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='코드')),
                ('category', models.CharField(max_length=100, verbose_name='공종')),
                ('name', models.CharField(max_length=200, verbose_name='명칭')),
                ('specification', models.CharField(max_length=200, verbose_name='규격')),
                ('unit', models.CharField(max_length=50, verbose_name='단위')),
                ('formula', models.TextField(verbose_name='산식')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='재료비단가')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='노무비단가')),
                ('expense_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='경비단가')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='합계단가')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IFCObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ifc_class', models.CharField(max_length=100)),
                ('spatial_container', models.CharField(blank=True, max_length=500)),
                ('quantities', models.JSONField(default=dict)),
                ('properties', models.JSONField(default=dict)),
                ('cost_items', models.TextField(blank=True, verbose_name='CostItems')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd_by_ifc.project')),
            ],
            options={
                'unique_together': {('project', 'global_id')},
            },
        ),
    ]
